handler: src/handlers/loans/get_status/get-status.handler
description: Returns current status of a loan application
iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:GetItem
      Resource:
          Fn::GetAtt: [LoanTable, Arn]
events:
    - http:
          path: /loans/{loanId}
          method: get
          cors: true
