export enum LoanStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  IDENTITY_VERIFICATION = 'IDENTITY_VERIFICATION',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  PENDING_SIGNATURE = 'PENDING_SIGNATURE',
  DISBURSEMENT_IN_PROGRESS = 'DISBURSEMENT_IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}
